apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: storage-demo
  namespace: apps-dev
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-retain
  resources:
    requests:
      storage: 1Gi
