apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
patches:
  - target:
      group: elasticsearch.k8s.elastic.co
      version: v1
      kind: Elasticsearch
      name: logging-es
    patch: |-
      - op: replace
        path: /spec/nodeSets/0/count
        value: 1
      - op: add
        path: /spec/nodeSets/0/config/node.store.allow_mmap
        value: false
      - op: replace
        path: /spec/nodeSets/0/podTemplate/spec/containers/0/resources
        value:
          requests: {cpu: 500m, memory: 1Gi}
          limits: {cpu: "1", memory: 2Gi}
      - op: remove
        path: /spec/nodeSets/0/podTemplate/spec/affinity
      - op: replace
        path: /spec/nodeSets/0/volumeClaimTemplates/0/spec/storageClassName
        value: local-retain
      - op: replace
        path: /spec/nodeSets/0/volumeClaimTemplates/0/spec/resources/requests/storage
        value: 10Gi
      - op: replace
        path: /spec/podDisruptionBudget/spec/minAvailable
        value: 0
  - target:
      group: kibana.k8s.elastic.co
      version: v1
      kind: Kibana
      name: logging-kibana
    patch: |-
      - op: replace
        path: /spec/count
        value: 1
      - op: remove
        path: /spec/podTemplate/spec/affinity
      - op: replace
        path: /spec/podTemplate/spec/containers/0/resources
        value:
          requests: {cpu: 250m, memory: 512Mi}
          limits: {cpu: "1", memory: 1Gi}
  - target:
      group: logstash.k8s.elastic.co
      version: v1alpha1
      kind: Logstash
      name: logging-logstash
    patch: |-
      - op: replace
        path: /spec/count
        value: 1
      - op: remove
        path: /spec/podTemplate/spec/affinity
      - op: replace
        path: /spec/podTemplate/spec/containers/0/env/0/value
        value: -Xms512m -Xmx512m -XX:MaxDirectMemorySize=512m
      - op: replace
        path: /spec/podTemplate/spec/containers/0/resources
        value:
          requests: {cpu: 500m, memory: 1Gi}
          limits: {cpu: "1", memory: 2Gi}
      - op: replace
        path: /spec/config/queue.max_bytes
        value: 1gb
      - op: replace
        path: /spec/config/dead_letter_queue.max_bytes
        value: 256mb
      - op: replace
        path: /spec/volumeClaimTemplates/0/spec/storageClassName
        value: local-retain
      - op: replace
        path: /spec/volumeClaimTemplates/0/spec/resources/requests/storage
        value: 3Gi
  - target:
      group: policy
      version: v1
      kind: PodDisruptionBudget
    patch: |-
      - op: replace
        path: /spec/minAvailable
        value: 0
